untis:
  kafka:
    topic: "sample"
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/untis"
    username: untis
    password: untis
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  kafka:
    bootstrap-servers: "localhost:9092"
  task:
    scheduling:
      pool:
        size: 5
